services:
  api:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ./docs:/docs
      - bundle_data:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: app_user
      DATABASE_PASSWORD: password
      DATABASE_NAME: app_development
      FRONTEND_ORIGIN: http://localhost:3001
    tty: true
    stdin_open: true

  db:
    image: postgres:18
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_development"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP
  openapi:
    build:
      context: ./docs
    volumes:
      - ./docs:/docs
      - openapi_node_modules:/docs/node_modules
    profiles: ["tools"]
  
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./docs/openapi.bundled.yaml:/openapi.yaml:ro
    environment:
      SWAGGER_JSON: /openapi.yaml
  web:
    build: ./web
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
      - pnpm_store:/app/.pnpm-store
    working_dir: /app
    ports:
      - "3001:3000"
    command: pnpm dev

volumes:
  postgres_data:
  pgadmin_data:
  bundle_data:
  openapi_node_modules:
  web_node_modules:
  pnpm_store: